[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
num-traits = "0.2.15"
rayon = "1.10.0"
rustc-hash = "2.0.0"
sscanf = "0.4.1"